export const CrawlerColors = {
  crawler_ultra_light_green: '#eafbd8',
  crawler_light_green: '#c9f59f',
  crawler_green: '#7cbf00',
  crawler_mega_dark_green: '#37794b',
  crawler_dark_green: '#469d23',
  crawler_blue_green: '#1ba5a2',
  crawler_ash_blue: '#31798f',
  crawler_battery_blue: '#2d6593',
  crawler_replacement_needed_blue: '#2d4092',
  crawler_grey: '#4e4e4e',
  crawler_dark_grey: '#afafaf',
  crawler_light_grey: '#bfbfbf',
  crawler_ultra_light_grey: '#efefef',
  crawler_light_red: '#e83a3e',
  crawler_red: '#bd171b',
  crawler_dark_red: '#ad070b',
  crawler_black: '#000000',
  crawler_light_black: '#2d3338',
  crawler_white: '#ffffff',
  crawler_yellow: '#fdc134',
};
